/*
 * 389. Find the Difference
 * Given two strings s and t which consist of only lowercase letters. String t is generated by random shuffling string s and then add one more letter at a random position. Find the letter that was added in t.
 * */

public class Solution {
    public char findTheDifference(String s, String t) {
	    char result = 0;
    	for (int i = 0; i < s.length(); i++) {
	    	result ^= s.charAt(i);
    	}
    	for (int i = 0; i < t.length(); i++) {
	    	result ^= t.charAt(i);
    	}
	    return result;
    }
}